### ISSUE TITLE
ใช้ไม่ได้กับ Wordpress 4.9

### ISSUE THREAD

**Issue by diehard27** [SeedThemes/seed-fonts#11]
ผมลองทำตามคลิปแล้ว เหมือนมันจะขยายขนาดฟอนต์ให้อย่างเดียว แต่ไม่ได้เปลี่ยนฟอนต์ให้ จะลองติดตั้งแบบ manual พบว่าใน theme ไม่มี path /theme/vendor/fonts ผมเลย สร้าง directory theme-name/vendor ขึ้นแล้ว copy directory "fonts" ไปวาง แต่ console ก็ยังแจ้งว่า Error 404 not found webfont อยู่

ต้องทำอย่างไรครับ

สภาพแวดล้อม
Win2008 server R2
IIS 7.5
PHP 5.4
MySQL 5.2

Edit ใช้ได้แล้วครับ ไม่ได้เพิ่ม MIME Type .woff, .woff2

**Comment by mennwebs** [comment]
แหะๆ คร้าบ :)
