### ISSUE TITLE
Fonts not loading IOS

### ISSUE THREAD

**Issue by chriscapisce** [SeedThemes/seed-fonts#13]
Hi, thanks for this plugin! I encounter an issue showing the font on IOS. I uploaded the font to my server using your tutorial but IOS doesn't show them..

`/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on May 20, 2019 */

@font-face {
    font-family: 'baar_metanoiabold';
    src: url('baarmetanoia-bold-webfont.eot');
    src: url('baarmetanoia-bold-webfont.eot?#iefix') format('embedded-opentype'),
         url('baarmetanoia-bold-webfont.woff2') format('woff2'),
         url('baarmetanoia-bold-webfont.woff') format('woff'),
         url('baarmetanoia-bold-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'baar_metanoiabold_italic';
    src: url('baarmetanoia-bolditalic-webfont.eot');
    src: url('baarmetanoia-bolditalic-webfont.eot?#iefix') format('embedded-opentype'),
         url('baarmetanoia-bolditalic-webfont.woff2') format('woff2'),
         url('baarmetanoia-bolditalic-webfont.woff') format('woff'),
         url('baarmetanoia-bolditalic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'baar_metanoiaitalic';
    src: url('baarmetanoia-italic-webfont.eot');
    src: url('baarmetanoia-italic-webfont.eot?#iefix') format('embedded-opentype'),
         url('baarmetanoia-italic-webfont.woff2') format('woff2'),
         url('baarmetanoia-italic-webfont.woff') format('woff'),
         url('baarmetanoia-italic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'baar_metanoiaregular';
    src: url('baarmetanoia-regular-webfont.eot');
    src: url('baarmetanoia-regular-webfont.eot?#iefix') format('embedded-opentype'),
         url('baarmetanoia-regular-webfont.woff2') format('woff2'),
         url('baarmetanoia-regular-webfont.woff') format('woff'),
         url('baarmetanoia-regular-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;

}`

**Comment by mennwebs** [comment]
Sorry for the delay.

You have to click on "family support" the all fonts will be same font-family name.

The code will be,

`@font-face {
font-family: 'baar_metanoia';
src: url('baarmetanoia-bold-webfont.eot');
src: url('baarmetanoia-bold-webfont.eot?#iefix') format('embedded-opentype'),
url('baarmetanoia-bold-webfont.woff2') format('woff2'),
url('baarmetanoia-bold-webfont.woff') format('woff'),
url('baarmetanoia-bold-webfont.ttf') format('truetype');
font-weight: bold;
font-style: normal;

}

@font-face {
font-family: 'baar_metanoia';
src: url('baarmetanoia-bolditalic-webfont.eot');
src: url('baarmetanoia-bolditalic-webfont.eot?#iefix') format('embedded-opentype'),
url('baarmetanoia-bolditalic-webfont.woff2') format('woff2'),
url('baarmetanoia-bolditalic-webfont.woff') format('woff'),
url('baarmetanoia-bolditalic-webfont.ttf') format('truetype');
font-weight: bold;
font-style: italic;

}

@font-face {
font-family: 'baar_metanoia';
src: url('baarmetanoia-italic-webfont.eot');
src: url('baarmetanoia-italic-webfont.eot?#iefix') format('embedded-opentype'),
url('baarmetanoia-italic-webfont.woff2') format('woff2'),
url('baarmetanoia-italic-webfont.woff') format('woff'),
url('baarmetanoia-italic-webfont.ttf') format('truetype');
font-weight: normal;
font-style: italic;

}

@font-face {
font-family: 'baar_metanoia';
src: url('baarmetanoia-regular-webfont.eot');
src: url('baarmetanoia-regular-webfont.eot?#iefix') format('embedded-opentype'),
url('baarmetanoia-regular-webfont.woff2') format('woff2'),
url('baarmetanoia-regular-webfont.woff') format('woff'),
url('baarmetanoia-regular-webfont.ttf') format('truetype');
font-weight: normal;
font-style: normal;

}`

Then, change this file name to "font.css"

and upload to folder named **baar_metanoia** such as 
**/wp-content/upload/fonts/baar_metanoia/**

**Comment by chriscapisce** [comment]
No problem, thank you so much! It works great!!
