### ISSUE TITLE
Loading an empty stylesheet?

### ISSUE THREAD

**Issue by siamkreative** [SeedThemes/seed-fonts#2]
See https://github.com/SeedThemes/seed-fonts/blob/master/seed-fonts.php#L163

Are you planning on improving the style of the options page or is this a leftover? If it's a leftover, make sure to remove the enqueue because it adds an extra HTTP request for nothing ;)

**Comment by vaivaisoft** [comment]
We have removed _seed-fonts-admin.css_ as your suggestions.
