### ISSUE TITLE
Are you using the Options API?

### ISSUE THREAD

**Issue by siamkreative** [SeedThemes/seed-fonts#3]
_Disclaimer: I'm not a PHP developer, so my judgment on this might be biased._

I didn't go through the whole code. But you should be using the [Options API](https://codex.wordpress.org/Options_API) to build the settings page.

I noticed that you're using `'.get_bloginfo( 'url' ).'/wp-admin/admin-post.php` as the form action of the options page ([here](https://github.com/SeedThemes/seed-fonts/blob/master/seed-fonts.php#L213)), which lead me to think that you are not using the Options API. But it looks like you are...

Usually with the Options API it should looks like this `<form action="options.php" method="post">`.

**Comment by vaivaisoft** [comment]
Thanks SiamKreative.

Of course, We are using Options API (get_option(), update_option()). However, We choose using [admin-post action](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_post_%28action%29) because the coding readability. We have never compare the performance with the old solution. If you have any suggestions for us, We'd be more than glad to hear.

**Comment by julien731** [comment]
I think that @SiamKreative was referring to the WordPress [Settings API](https://codex.wordpress.org/Settings_API) which you're not using for your options page.

Honestly, using JavaScript to handle options when the Settings API is made just for that seems a little old school. Also, you're relying on unsafe methods for things such as getting the admin page URL in the form action.

I'm gonna propose a PR that replaces the JS function by the Settings API and let you decide what works best.

Finally, I don't really understand the use of the `Seed_Fonts` class. All its methods are empty, and you even hook those empty methods on plugin activation and deactivation.

EDIT: PR #4 pushed

**Comment by vaivaisoft** [comment]
We have pushed the new version using Settings API as your suggestions.

Thank you very much for your sharing.
