### ISSUE TITLE
Conflict with Amazon S3 Upload plugins 

### ISSUE THREAD

**Issue by korrio** [SeedThemes/seed-fonts#5]
ตอนที่จะ execute ผ่าน CLI ใช้คำสั่ง 
wp s3-uploads upload-directory videos /videos --allow-root

มันจะบอกว่า syntax error ตรงบรรทัดที่ 421 ของไฟล์ [seed-fonts.php](https://github.com/SeedThemes/seed-fonts/blob/master/seed-fonts.php#L421)

วิธี workaround ก็คือ ผมต้องลบ Seed Fonts ออกก่อนถึงจะ สามารถรันคำสั่งนั้นได้ (deactivate มันก็ไม่ให้รัน error แบบเดิม ไม่รู้มันไปยุ่งอะไรกับ Seed Fonts) แล้วพอรันเสร็จก็ค่อยลง Seed Fonts ใหม่อีกที

**Comment by papazeal** [comment]
น่าจะเกิดจาก PHP short open tag ครับ

https://github.com/SeedThemes/seed-fonts/blob/master/seed-fonts.php#L141

ต้องแก้จาก `<?` เป็น `<?php`

**Comment by mennwebs** [comment]
ขอบคุณมากเลยครับผม :D
