### ISSUE TITLE
Add body class for body text

### ISSUE THREAD

**Issue by mennwebs** [SeedThemes/seed-fonts#7]
จ๋ง ฝากเพิ่ม body class ให้กับ body text หน่อยสิ บางฟอนต์ใช้แล้วอยากปรับนิดหน่อยน่ะ

**Comment by vaivaisoft** [comment]
แก้แล้วเน่อ push ไปแล้ว

ไม่ได้ปรับรุ่นนะ เพราะเช้าใจว่าทางพี่ต้องแก้อะไรด้วย เดี๋ยวรุ่นจะวิ่งโดยไม่จำเป็น

**Comment by mennwebs** [comment]
ขอบคุณมากจ๋ง :D
